export const UserRoutes = {
  DASHBOARD: "/user",
  CONTACTS: "/user/contacts",
  BROADCAST: "/user/broadcast",
  BROADCAST_MESSAGE: "/user/broadcast/message",
  BROADCAST_TEMPLATE: "/user/broadcast/template",
  BROADCAST_MESSAGE_SEND: "/user/broadcast/message/send",
  USER_CONTACTS_INDEX: "/user/contacts",
  ACCOUNT: "/user/account",
  LIST_AUTOMATION: "/user/automation",
  GROUP_AUTOMATION: "/user/automation/group",
  GROUP_TEMPLATE: "/user/automation/template",
  FORM: "/user/form",
  FORM_CREATE: "/user/form/create",
  FORM_ENTRIES: "/user/form/entries",
  SUBSCRIPTION: "/user/subscriptions",
  CHAT_BOT: "/user/chatbot",
  TEAMS: "/user/teams",
  SIGNUP: "/signup",
  LOGIN: "/",
};
